version: '3'
services:
  api-app:
    image: davdportillo/winning-station:latest 
    ports:
      - "1010:8080"
    depends_on:
      - db
    restart: always
  db:
    image: "mysql:8.0"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=VictoryStation
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
