version: '3'
services:
  api-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: "mysql:8.0"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=VictoryStation
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
